# Generated by Django 5.2.3 on 2025-09-18 17:44

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Constancia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio del Evento')),
                ('fecha_termino', models.DateField(verbose_name='Fecha de Término del Evento')),
                ('duracion_en_horas', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Duración (Horas)')),
                ('fecha_emision', models.DateField(auto_now_add=True, verbose_name='Fecha de Emisión')),
                ('codigo_verificacion', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Código de Verificación')),
                ('es_webinar', models.BooleanField(default=False, verbose_name='¿Es de Webinar?')),
                ('fecha_vencimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Vencimiento')),
                ('token_encuesta', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
            options={
                'verbose_name': 'Constancia',
                'verbose_name_plural': 'Constancias',
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre del Curso')),
            ],
            options={
                'verbose_name': 'Definición de Curso',
                'verbose_name_plural': 'Definiciones de Cursos',
            },
        ),
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre de la Institución')),
                ('ubicacion', models.CharField(blank=True, max_length=255, verbose_name='Ubicación (ej. Ciudad, Estado)')),
            ],
            options={
                'verbose_name': 'Institución',
                'verbose_name_plural': 'Instituciones',
            },
        ),
        migrations.CreateModel(
            name='Evaluador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('cargo', models.CharField(blank=True, max_length=255, verbose_name='Cargo o Puesto')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos/', verbose_name='Foto de Perfil')),
                ('firma_digital', models.ImageField(blank=True, null=True, upload_to='firmas/', verbose_name='Firma Digital (PNG)')),
                ('es_gerente', models.BooleanField(default=False, verbose_name='¿Es el Gerente que firma por defecto?')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='EncuestaRespuesta',
            fields=[
                ('constancia', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.constancia')),
                ('nombre_completo', models.CharField(max_length=255, verbose_name='1. Ingresa tu nombre completo')),
                ('email', models.EmailField(max_length=254, verbose_name='2. Correo electrónico')),
                ('satisfaccion_general', models.TextField(verbose_name='3. En términos generales, ¿Qué grado de satisfacción experimentó con el seminario web?')),
                ('evaluacion_general', models.TextField(verbose_name='4. En general, ¿Cómo evaluaría el seminario web?')),
                ('aspectos_interesantes', models.TextField(verbose_name='5. ¿Qué aspectos del seminario web le pareció más interesante?')),
                ('aspectos_no_gustaron', models.TextField(blank=True, verbose_name='6. ¿Qué aspectos del seminario web no le gustó?')),
                ('informacion_valiosa', models.TextField(verbose_name='7. ¿Cuál considera que es la información más significativa o valiosa que obtuvo?')),
                ('organizacion', models.CharField(choices=[('Extremadamente organizado', 'Extremadamente organizado'), ('Muy organizado', 'Muy organizado'), ('Algo organizado', 'Algo organizado'), ('No tan organizado', 'No tan organizado'), ('Nada organizado', 'Nada organizado')], max_length=50, verbose_name='8. ¿Cómo calificaría el nivel de organización?')),
                ('duracion', models.CharField(choices=[('Demasiada larga', 'Demasiada larga'), ('Muy larga', 'Muy larga'), ('Apenas lo justo', 'Apenas lo justo'), ('Muy corta', 'Muy corta'), ('Demasiada corta', 'Demasiada corta')], max_length=50, verbose_name='9. ¿Cómo considera la duración del seminario web?')),
                ('recomendacion', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], verbose_name='10. En una escala del 1 al 10, ¿cuál es la probabilidad de que recomiende nuestros seminarios web?')),
                ('temas_futuros', models.TextField(blank=True, verbose_name='11. ¿Qué temas le gustaría que se aborden en los seminarios web futuros?')),
                ('horario_preferido', models.CharField(choices=[('Mañana', 'Mañana'), ('Tarde', 'Tarde'), ('Noche', 'Noche')], max_length=20, verbose_name='12. ¿Cuál sería el horario más conveniente?')),
                ('dia_preferido', models.CharField(choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miércoles', 'Miércoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes')], max_length=20, verbose_name='13. ¿Qué día de la semana considera más conveniente?')),
                ('comentarios_adicionales', models.TextField(blank=True, verbose_name='14. ¿Desea compartir algún comentario o sugerencia adicional?')),
                ('interes_productos', models.BooleanField(default=False, verbose_name=' ¿Le interesaría recibir más información sobre los productos de EUROIMMUN?')),
                ('fecha_respuesta', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='constancia',
            name='firma_especialista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='constancias_como_especialista', to=settings.AUTH_USER_MODEL, verbose_name='Firma del Especialista'),
        ),
        migrations.AddField(
            model_name='constancia',
            name='firma_gerente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='constancias_como_gerente', to=settings.AUTH_USER_MODEL, verbose_name='Firma del Gerente'),
        ),
        migrations.AddField(
            model_name='constancia',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.curso', verbose_name='Curso'),
        ),
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=255)),
                ('email', models.EmailField(help_text='El correo debe ser único para cada participante.', max_length=254, unique=True)),
                ('titulo', models.CharField(blank=True, choices=[('', 'Seleccionar Título...'), ('Lic.', 'Licenciado(a)'), ('Ing.', 'Ingeniero(a)'), ('Dr.', 'Doctor(a)'), ('Mtro.', 'Maestro(a)'), ('Q.F.B.', 'Químico Farmacéutico Biólogo'), ('Q.B.P.', 'Químico Bacteriólogo Parasitólogo'), ('Otro', 'Otro (sin título)')], default='', max_length=50, verbose_name='Título Profesional')),
                ('institucion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.institucion', verbose_name='Institución de Origen')),
            ],
            options={
                'verbose_name': 'Participante',
                'verbose_name_plural': 'Participantes',
            },
        ),
        migrations.AddField(
            model_name='constancia',
            name='participante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.participante', verbose_name='Participante'),
        ),
        migrations.CreateModel(
            name='LeadVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.curso')),
                ('participante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.participante')),
            ],
            options={
                'unique_together': {('participante', 'curso')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='constancia',
            unique_together={('participante', 'curso', 'fecha_inicio')},
        ),
    ]
