# Generated by Django 5.2.5 on 2025-08-21 16:19

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre del Curso')),
            ],
            options={
                'verbose_name': 'Definición de Curso',
                'verbose_name_plural': 'Definiciones de Cursos',
            },
        ),
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=255)),
                ('email', models.EmailField(help_text='El correo debe ser único para cada participante.', max_length=254, unique=True)),
                ('titulo', models.CharField(blank=True, max_length=50, verbose_name='Título Profesional (ej. Q.F.B.)')),
            ],
            options={
                'verbose_name': 'Participante',
                'verbose_name_plural': 'Participantes',
            },
        ),
        migrations.CreateModel(
            name='Evaluador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('cargo', models.CharField(blank=True, max_length=255, verbose_name='Cargo o Puesto')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos/', verbose_name='Foto de Perfil')),
                ('firma_digital', models.ImageField(blank=True, null=True, upload_to='firmas/', verbose_name='Firma Digital (PNG)')),
                ('es_gerente', models.BooleanField(default=False, verbose_name='¿Es el Gerente que firma por defecto?')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Constancia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio del Evento')),
                ('fecha_termino', models.DateField(verbose_name='Fecha de Término del Evento')),
                ('duracion_en_horas', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Duración (Horas)')),
                ('fecha_emision', models.DateField(auto_now_add=True, verbose_name='Fecha de Emisión')),
                ('codigo_verificacion', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Código de Verificación')),
                ('firma_especialista', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='constancias_como_especialista', to=settings.AUTH_USER_MODEL, verbose_name='Firma del Especialista')),
                ('firma_gerente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='constancias_como_gerente', to=settings.AUTH_USER_MODEL, verbose_name='Firma del Gerente')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.curso', verbose_name='Curso')),
                ('participante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.participante', verbose_name='Participante')),
            ],
            options={
                'verbose_name': 'Constancia',
                'verbose_name_plural': 'Constancias',
                'unique_together': {('participante', 'curso', 'fecha_inicio')},
            },
        ),
    ]
