# Generated by Django 5.2.5 on 2025-08-21 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participante',
            name='institucion',
            field=models.CharField(default=1, max_length=255, verbose_name='Institución de Origen'),
            preserve_default=False,
        ),
    ]
