# Generated by Django 5.2.5 on 2026-09-03 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='constancia',
            name='tipo',
            field=models.CharField(choices=[('curso', 'Curso'), ('webinar', 'Webinar'), ('teorica', 'Capacitación teórica')], default='curso', max_length=20, verbose_name='Tipo de constancia'),
        ),
    ]
