# Generated by Django 5.2.5 on 2025-08-26 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_institucion_alter_participante_institucion'),
    ]

    operations = [
        migrations.AddField(
            model_name='constancia',
            name='es_webinar',
            field=models.BooleanField(default=False, verbose_name='¿Es de Webinar?'),
        ),
    ]
