# Generated by Django 5.2.5 on 2025-08-27 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_constancia_es_webinar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participante',
            name='titulo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Título Profesional (ej. Q.F.B.)'),
        ),
    ]
