# Generated by Django 5.2.5 on 2025-08-27 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_participante_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='constancia',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Vencimiento'),
        ),
    ]
