# Generated by Django 5.2.3 on 2025-09-17 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_constancia_fecha_vencimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participante',
            name='titulo',
            field=models.CharField(blank=True, choices=[('', 'Seleccionar Título...'), ('Lic.', 'Licenciado(a)'), ('Ing.', 'Ingeniero(a)'), ('Dr.', 'Doctor(a)'), ('Mtro.', 'Maestro(a)'), ('Q.F.B.', 'Químico Farmacéutico Biólogo'), ('Q.B.P.', 'Químico Bacteriólogo Parasitólogo'), ('Otro', 'Otro (sin título)')], default='', max_length=50, verbose_name='Título Profesional'),
        ),
    ]
